DELETE FROM AUTHORS_IN_TEXTBOOK;
DELETE FROM COURSE_OF_TEXTBOOK;
DELETE FROM POSTING;
DELETE FROM SELLERS_SELL_TEXTBOOK;
DELETE FROM SELLERS;
DELETE FROM USERS;
DELETE FROM TEXTBOOKS;
DELETE FROM COURSE;